[build]
  publish = "glassskin-push"
  base    = "glassskin-push"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Service-Worker-Allowed = "/"
